services:

  db:
    image: postgres:14-alpine
    container_name: servlets-rs-postgres-container
    ports:
      - "6001:5432"
    environment:
      - POSTGRES_DB=servlets_rs
      - POSTGRES_USER=user3827
      - POSTGRES_PASSWORD=_Fr5Yd5Yup